services:
  app:
    build:
      context: .
      target: prod
    container_name: barbearia_app_prod
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      SERVER_NAME: barbearia-oliveira-alves.matheushrm.dev
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - app_storage:/app/storage
      - caddy_data:/data
      - caddy_config:/config
    stop_grace_period: 30s
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: barbearia_postgres_prod
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  app_storage:
  caddy_data:
  caddy_config:
  postgres_data:
